Project2
Facele5s/JavaHomework pull request #7
Opened 2023-11-05 16:35 UTC by Facele5s

2023-12-03 14:41 UTC, strelchm requested changes

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Main.java
> +            LOGGER.info(e);
Для ошибки, наверное, другой уровень логирования подойдет

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Main.java
> +        } catch (WrongSizeException e) {
Возможно, можно совместить два catch в один

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_structure/Maze.java
> +    public Maze(int width, int height) throws WrongSizeException {
Конструктор сильно перегружен - здесь и валидация и создание лабиринта. Возможно, следует разбить на методы, а возможно и классы - напр., валидатор

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_creation/Digger.java
> +    Cell getRandomCell(Cell current) throws WrongCellException;
исходя из названия - взятие любой ячейки. Мб лучше назвать _getRandomNeibhourd_?

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_creation/Digger.java
> +    void digCell(Cell cell);
нужен ли данный метод в интерфейсе, если мы "копаем" только внутри реализации данного класса

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_output/MazePrinter.java
> +    public void printMaze() throws WrongCellException {
Трудно понять исходя из вывода, что происходит. Похоже на тетрис. Можно ли отформатировать вывод? Например, добавив пробелы между cell-ами - будет значительно понятнее

![image](https://github.com/Facele5s/JavaHomework/assets/23243577/f8bf5c2b-3c14-4ce2-92df-2fdff578fff6)

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_solution/MazePathFinder.java
> +    public void findPath(Cell startCell, Cell finish) throws WrongCellException {
not important: Исходя из названия метода совсем не понятно, что идет обновление _Maze_

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_solution/PathFinder.java
> +    List<Cell> getNearestCells(Cell current) throws WrongCellException;
Почему этот метод в интерфейсе? Кроме реализаций этого интерфейса еще где-то используется и если да, то для чего?

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Main.java
> +            Maze maze = new Maze(10, 10);
На будущее: как по основному коду, так и по тестам - лучше использовать интерфейсы вместо их реализаций - для масштабирования системы. Использование методов конкретных реализаций в тестах - не есть хорошо, см. SOLID

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_solution/MazePathFinder.java
> +        Collections.reverse(xCoordinates);
эти две строки непонятны - данные коллекции после выхода из метода не используются

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Main.java
> +            Maze maze = new Maze(10, 10);
или зачем тогда нужны интерфейсы, если в коде они не юзаются?

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_creation/ControlledRandom.java
> +package edu.project2.Maze_creation;
Такой нейминг пакетов не общепринятый (возможно он взят из C#?). Для java более принятым был бы кодстайл в стиле _edu.project2.maze.creation_. Для подробностей можно посмотреть javadoc

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_creation/ControlledRandom.java
> +package edu.project2.Maze_creation;
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_creation/ControlledRandom.java
> +package edu.project2.Maze_creation;
Похоже, что все таки из C#, т к package by feature разнесение классов похоже на c#/.net-тему

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Exceptions/WrongCellException.java
> +package edu.project2.Exceptions;
почему в MR коммиты, которые к задаче не относятся?

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_structure/Cell.java
> +    private boolean isPath;
При хранении пути в ячейке мы ограничиваемся, что у нас будет одно прохождение лабиринта. Мы сделали хорошо, что разделили генерацию лабиринта и прохождение в методе main. И преимуществом такого разделения должна быть независимость данных стадий, а также переиспользование. Можем сгенерировать лабиринт, потом пройти один раз, потом еще раз пройти. Сами ячейки при этом будут иметь состояние стена/не стена, но путь при этом хорошо бы вынести. Будет хорошо, если подумаете в эту сторону.

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_structure/Cell.java
> +    private boolean isPath;
получается, что лабиринт имеет отношение один-ко-многим к его прохождениям

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Maze_structure/Cell.java
> +    private boolean isPath;
В задании был специальный интерфейс под это дело:
`public interface Solver {
   List<Coordinate> solve(Maze maze, Coordinate start, Coordinate end);
}
`

2023-12-03 14:41 UTC, strelchm commented on src/main/java/edu/project2/Exceptions/WrongCellException.java
> +package edu.project2.Exceptions;
![image](https://github.com/Facele5s/JavaHomework/assets/23243577/b633afc4-ffb9-4c2b-b2d0-fca81d5bbf74)
покрытие кода из-за этого считается неверно

2023-12-25 14:20 UTC, Facele5s commented on src/main/java/edu/project2/Maze_solution/MazePathFinder.java
> +        Collections.reverse(xCoordinates);
Эти коллекции используются для проверки правильности поиска пути в тестах

2023-12-25 14:31 UTC, Facele5s commented on src/main/java/edu/project2/Exceptions/WrongCellException.java
> +package edu.project2.Exceptions;
К сожалению, немного напортачил с гитом, и это вылилось вот в такую ситуацию

2024-01-06 17:10 UTC, strelchm approved these changes

2024-01-07 20:51 UTC, merged